/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiscoveryFilters {
  'interests' : Array<string>,
  'minAge' : bigint,
  'genderPref' : [] | [Gender],
  'maxAge' : bigint,
}
export interface DiscoveryPage {
  'nextOffset' : [] | [bigint],
  'profiles' : Array<Profile>,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null } |
  { 'nonBinary' : null };
export interface Match {
  'createdAt' : Timestamp,
  'matchId' : MatchId,
  'user1' : UserId,
  'user2' : UserId,
  'superLiked' : boolean,
}
export type MatchId = string;
export interface Message {
  'id' : MessageId,
  'text' : string,
  'readByRecipient' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'matchId' : MatchId,
}
export type MessageId = bigint;
export interface Profile {
  'age' : bigint,
  'bio' : string,
  'height' : [] | [bigint],
  'filters' : DiscoveryFilters,
  'photoKeys' : Array<ExternalBlob>,
  'profilePicUrl' : [] | [string],
  'principal' : UserId,
  'interests' : Array<string>,
  'isPremium' : boolean,
  'coverPicUrl' : [] | [string],
  'premiumActivatedAt' : [] | [bigint],
  'name' : string,
  'createdAt' : Timestamp,
  'superLikesRemaining' : bigint,
  'isDemo' : boolean,
  'subscriptionStatus' : string,
  'genderPreference' : [] | [Gender],
  'gender' : Gender,
  'profileComplete' : boolean,
  'lastSeen' : Timestamp,
  'location' : string,
}
export interface ProfileInput {
  'age' : bigint,
  'bio' : string,
  'height' : [] | [bigint],
  'photoKeys' : Array<ExternalBlob>,
  'interests' : Array<string>,
  'name' : string,
  'genderPreference' : [] | [Gender],
  'gender' : Gender,
  'coverPic' : [] | [string],
  'profilePic' : [] | [string],
  'location' : string,
}
export type SwipeAction = { 'like' : null } |
  { 'pass' : null } |
  { 'superLike' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'activatePremium' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProfile' : ActorMethod<[ProfileInput], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDemoProfile' : ActorMethod<[string], [] | [Profile]>,
  'getDemoProfileCount' : ActorMethod<[], bigint>,
  'getDiscoveryProfiles' : ActorMethod<[bigint, bigint], DiscoveryPage>,
  'getFilters' : ActorMethod<[], [] | [DiscoveryFilters]>,
  'getMatch' : ActorMethod<[UserId], [] | [Match]>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getMessages' : ActorMethod<[MatchId, bigint, bigint], Array<Message>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getPremiumStatus' : ActorMethod<
    [],
    {
      'isPremium' : boolean,
      'premiumActivatedAt' : [] | [bigint],
      'subscriptionStatus' : string,
    }
  >,
  'getProfile' : ActorMethod<[UserId], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessagesRead' : ActorMethod<[MatchId], undefined>,
  'recordDemoSwipe' : ActorMethod<
    [string, SwipeAction],
    { 'matchId' : [] | [MatchId], 'matched' : boolean }
  >,
  'recordSwipe' : ActorMethod<
    [UserId, SwipeAction],
    { 'matchId' : [] | [MatchId], 'matched' : boolean }
  >,
  'saveFilters' : ActorMethod<[DiscoveryFilters], undefined>,
  'seedDemoProfiles' : ActorMethod<[], string>,
  'sendMessage' : ActorMethod<[MatchId, string], Message>,
  'updateProfile' : ActorMethod<[ProfileInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];