/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'nonBinary' : IDL.Null,
});
export const ProfileInput = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'height' : IDL.Opt(IDL.Nat),
  'photoKeys' : IDL.Vec(ExternalBlob),
  'interests' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'genderPreference' : IDL.Opt(Gender),
  'gender' : Gender,
  'coverPic' : IDL.Opt(IDL.Text),
  'profilePic' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const DiscoveryFilters = IDL.Record({
  'interests' : IDL.Vec(IDL.Text),
  'minAge' : IDL.Nat,
  'genderPref' : IDL.Opt(Gender),
  'maxAge' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'height' : IDL.Opt(IDL.Nat),
  'filters' : DiscoveryFilters,
  'photoKeys' : IDL.Vec(ExternalBlob),
  'profilePicUrl' : IDL.Opt(IDL.Text),
  'principal' : UserId,
  'interests' : IDL.Vec(IDL.Text),
  'isPremium' : IDL.Bool,
  'coverPicUrl' : IDL.Opt(IDL.Text),
  'premiumActivatedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'superLikesRemaining' : IDL.Nat,
  'isDemo' : IDL.Bool,
  'subscriptionStatus' : IDL.Text,
  'genderPreference' : IDL.Opt(Gender),
  'gender' : Gender,
  'profileComplete' : IDL.Bool,
  'lastSeen' : Timestamp,
  'location' : IDL.Text,
});
export const DiscoveryPage = IDL.Record({
  'nextOffset' : IDL.Opt(IDL.Nat),
  'profiles' : IDL.Vec(Profile),
});
export const MatchId = IDL.Text;
export const Match = IDL.Record({
  'createdAt' : Timestamp,
  'matchId' : MatchId,
  'user1' : UserId,
  'user2' : UserId,
  'superLiked' : IDL.Bool,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'text' : IDL.Text,
  'readByRecipient' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'matchId' : MatchId,
});
export const SwipeAction = IDL.Variant({
  'like' : IDL.Null,
  'pass' : IDL.Null,
  'superLike' : IDL.Null,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activatePremium' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProfile' : IDL.Func([ProfileInput], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDemoProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
  'getDemoProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDiscoveryProfiles' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [DiscoveryPage],
      ['query'],
    ),
  'getFilters' : IDL.Func([], [IDL.Opt(DiscoveryFilters)], ['query']),
  'getMatch' : IDL.Func([UserId], [IDL.Opt(Match)], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getMessages' : IDL.Func(
      [MatchId, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPremiumStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'isPremium' : IDL.Bool,
          'premiumActivatedAt' : IDL.Opt(IDL.Int),
          'subscriptionStatus' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesRead' : IDL.Func([MatchId], [], []),
  'recordDemoSwipe' : IDL.Func(
      [IDL.Text, SwipeAction],
      [IDL.Record({ 'matchId' : IDL.Opt(MatchId), 'matched' : IDL.Bool })],
      [],
    ),
  'recordSwipe' : IDL.Func(
      [UserId, SwipeAction],
      [IDL.Record({ 'matchId' : IDL.Opt(MatchId), 'matched' : IDL.Bool })],
      [],
    ),
  'saveFilters' : IDL.Func([DiscoveryFilters], [], []),
  'seedDemoProfiles' : IDL.Func([], [IDL.Text], []),
  'sendMessage' : IDL.Func([MatchId, IDL.Text], [Message], []),
  'updateProfile' : IDL.Func([ProfileInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'nonBinary' : IDL.Null,
  });
  const ProfileInput = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'height' : IDL.Opt(IDL.Nat),
    'photoKeys' : IDL.Vec(ExternalBlob),
    'interests' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'genderPreference' : IDL.Opt(Gender),
    'gender' : Gender,
    'coverPic' : IDL.Opt(IDL.Text),
    'profilePic' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const DiscoveryFilters = IDL.Record({
    'interests' : IDL.Vec(IDL.Text),
    'minAge' : IDL.Nat,
    'genderPref' : IDL.Opt(Gender),
    'maxAge' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'height' : IDL.Opt(IDL.Nat),
    'filters' : DiscoveryFilters,
    'photoKeys' : IDL.Vec(ExternalBlob),
    'profilePicUrl' : IDL.Opt(IDL.Text),
    'principal' : UserId,
    'interests' : IDL.Vec(IDL.Text),
    'isPremium' : IDL.Bool,
    'coverPicUrl' : IDL.Opt(IDL.Text),
    'premiumActivatedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'superLikesRemaining' : IDL.Nat,
    'isDemo' : IDL.Bool,
    'subscriptionStatus' : IDL.Text,
    'genderPreference' : IDL.Opt(Gender),
    'gender' : Gender,
    'profileComplete' : IDL.Bool,
    'lastSeen' : Timestamp,
    'location' : IDL.Text,
  });
  const DiscoveryPage = IDL.Record({
    'nextOffset' : IDL.Opt(IDL.Nat),
    'profiles' : IDL.Vec(Profile),
  });
  const MatchId = IDL.Text;
  const Match = IDL.Record({
    'createdAt' : Timestamp,
    'matchId' : MatchId,
    'user1' : UserId,
    'user2' : UserId,
    'superLiked' : IDL.Bool,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'text' : IDL.Text,
    'readByRecipient' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'matchId' : MatchId,
  });
  const SwipeAction = IDL.Variant({
    'like' : IDL.Null,
    'pass' : IDL.Null,
    'superLike' : IDL.Null,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activatePremium' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProfile' : IDL.Func([ProfileInput], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDemoProfile' : IDL.Func([IDL.Text], [IDL.Opt(Profile)], ['query']),
    'getDemoProfileCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDiscoveryProfiles' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [DiscoveryPage],
        ['query'],
      ),
    'getFilters' : IDL.Func([], [IDL.Opt(DiscoveryFilters)], ['query']),
    'getMatch' : IDL.Func([UserId], [IDL.Opt(Match)], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getMessages' : IDL.Func(
        [MatchId, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPremiumStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'isPremium' : IDL.Bool,
            'premiumActivatedAt' : IDL.Opt(IDL.Int),
            'subscriptionStatus' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getProfile' : IDL.Func([UserId], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesRead' : IDL.Func([MatchId], [], []),
    'recordDemoSwipe' : IDL.Func(
        [IDL.Text, SwipeAction],
        [IDL.Record({ 'matchId' : IDL.Opt(MatchId), 'matched' : IDL.Bool })],
        [],
      ),
    'recordSwipe' : IDL.Func(
        [UserId, SwipeAction],
        [IDL.Record({ 'matchId' : IDL.Opt(MatchId), 'matched' : IDL.Bool })],
        [],
      ),
    'saveFilters' : IDL.Func([DiscoveryFilters], [], []),
    'seedDemoProfiles' : IDL.Func([], [IDL.Text], []),
    'sendMessage' : IDL.Func([MatchId, IDL.Text], [Message], []),
    'updateProfile' : IDL.Func([ProfileInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };