/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Match {
    createdAt: Timestamp;
    matchId: MatchId;
    user1: UserId;
    user2: UserId;
    superLiked: boolean;
}
export interface Profile {
    age: bigint;
    bio: string;
    height?: bigint;
    filters: DiscoveryFilters;
    photoKeys: Array<ExternalBlob>;
    profilePicUrl?: string;
    principal: UserId;
    interests: Array<string>;
    isPremium: boolean;
    coverPicUrl?: string;
    premiumActivatedAt?: bigint;
    name: string;
    createdAt: Timestamp;
    superLikesRemaining: bigint;
    isDemo: boolean;
    subscriptionStatus: string;
    genderPreference?: Gender;
    gender: Gender;
    profileComplete: boolean;
    lastSeen: Timestamp;
    location: string;
}
export type MatchId = string;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DiscoveryPage {
    nextOffset?: bigint;
    profiles: Array<Profile>;
}
export type UserId = Principal;
export interface DiscoveryFilters {
    interests: Array<string>;
    minAge: bigint;
    genderPref?: Gender;
    maxAge: bigint;
}
export type MessageId = bigint;
export interface Message {
    id: MessageId;
    text: string;
    readByRecipient: boolean;
    sender: UserId;
    sentAt: Timestamp;
    matchId: MatchId;
}
export interface ProfileInput {
    age: bigint;
    bio: string;
    height?: bigint;
    photoKeys: Array<ExternalBlob>;
    interests: Array<string>;
    name: string;
    genderPreference?: Gender;
    gender: Gender;
    coverPic?: string;
    profilePic?: string;
    location: string;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male",
    nonBinary = "nonBinary"
}
export enum SwipeAction {
    like = "like",
    pass = "pass",
    superLike = "superLike"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    activatePremium(paymentRef: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProfile(input: ProfileInput): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getDemoProfile(demoKey: string): Promise<Profile | null>;
    getDemoProfileCount(): Promise<bigint>;
    getDiscoveryProfiles(offset: bigint, limit: bigint): Promise<DiscoveryPage>;
    getFilters(): Promise<DiscoveryFilters | null>;
    getMatch(targetPrincipal: UserId): Promise<Match | null>;
    getMatches(): Promise<Array<Match>>;
    getMessages(matchId: MatchId, offset: bigint, limit: bigint): Promise<Array<Message>>;
    getMyProfile(): Promise<Profile | null>;
    getPremiumStatus(): Promise<{
        isPremium: boolean;
        premiumActivatedAt?: bigint;
        subscriptionStatus: string;
    }>;
    getProfile(user: UserId): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    markMessagesRead(matchId: MatchId): Promise<void>;
    recordDemoSwipe(demoKey: string, action: SwipeAction): Promise<{
        matchId?: MatchId;
        matched: boolean;
    }>;
    recordSwipe(targetPrincipal: UserId, action: SwipeAction): Promise<{
        matchId?: MatchId;
        matched: boolean;
    }>;
    saveFilters(filters: DiscoveryFilters): Promise<void>;
    seedDemoProfiles(): Promise<string>;
    sendMessage(matchId: MatchId, text: string): Promise<Message>;
    updateProfile(input: ProfileInput): Promise<void>;
}
import type { DiscoveryFilters as _DiscoveryFilters, DiscoveryPage as _DiscoveryPage, ExternalBlob as _ExternalBlob, Gender as _Gender, Match as _Match, MatchId as _MatchId, Profile as _Profile, ProfileInput as _ProfileInput, SwipeAction as _SwipeAction, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async activatePremium(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePremium(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProfile(arg0: ProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(await to_candid_ProfileInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(await to_candid_ProfileInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDemoProfile(arg0: string): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDemoProfileCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoProfileCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoProfileCount();
            return result;
        }
    }
    async getDiscoveryProfiles(arg0: bigint, arg1: bigint): Promise<DiscoveryPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscoveryProfiles(arg0, arg1);
                return from_candid_DiscoveryPage_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscoveryProfiles(arg0, arg1);
            return from_candid_DiscoveryPage_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilters(): Promise<DiscoveryFilters | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilters();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilters();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: UserId): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return result;
        }
    }
    async getMessages(arg0: MatchId, arg1: bigint, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1, arg2);
            return result;
        }
    }
    async getMyProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPremiumStatus(): Promise<{
        isPremium: boolean;
        premiumActivatedAt?: bigint;
        subscriptionStatus: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPremiumStatus();
                return from_candid_record_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPremiumStatus();
            return from_candid_record_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: UserId): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessagesRead(arg0: MatchId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async recordDemoSwipe(arg0: string, arg1: SwipeAction): Promise<{
        matchId?: MatchId;
        matched: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDemoSwipe(arg0, to_candid_SwipeAction_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_record_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDemoSwipe(arg0, to_candid_SwipeAction_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_record_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordSwipe(arg0: UserId, arg1: SwipeAction): Promise<{
        matchId?: MatchId;
        matched: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSwipe(arg0, to_candid_SwipeAction_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_record_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSwipe(arg0, to_candid_SwipeAction_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_record_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveFilters(arg0: DiscoveryFilters): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFilters(to_candid_DiscoveryFilters_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFilters(to_candid_DiscoveryFilters_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedDemoProfiles(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDemoProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDemoProfiles();
            return result;
        }
    }
    async sendMessage(arg0: MatchId, arg1: string): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: ProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(await to_candid_ProfileInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(await to_candid_ProfileInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DiscoveryFilters_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscoveryFilters): DiscoveryFilters {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_DiscoveryPage_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscoveryPage): Promise<DiscoveryPage> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Profile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Promise<Profile> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Promise<Profile | null> {
    return value.length === 0 ? null : await from_candid_Profile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Gender]): Gender | null {
    return value.length === 0 ? null : from_candid_Gender_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiscoveryFilters]): DiscoveryFilters | null {
    return value.length === 0 ? null : from_candid_DiscoveryFilters_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchId]): MatchId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    height: [] | [bigint];
    filters: _DiscoveryFilters;
    photoKeys: Array<_ExternalBlob>;
    profilePicUrl: [] | [string];
    principal: _UserId;
    interests: Array<string>;
    isPremium: boolean;
    coverPicUrl: [] | [string];
    premiumActivatedAt: [] | [bigint];
    name: string;
    createdAt: _Timestamp;
    superLikesRemaining: bigint;
    isDemo: boolean;
    subscriptionStatus: string;
    genderPreference: [] | [_Gender];
    gender: _Gender;
    profileComplete: boolean;
    lastSeen: _Timestamp;
    location: string;
}): Promise<{
    age: bigint;
    bio: string;
    height?: bigint;
    filters: DiscoveryFilters;
    photoKeys: Array<ExternalBlob>;
    profilePicUrl?: string;
    principal: UserId;
    interests: Array<string>;
    isPremium: boolean;
    coverPicUrl?: string;
    premiumActivatedAt?: bigint;
    name: string;
    createdAt: Timestamp;
    superLikesRemaining: bigint;
    isDemo: boolean;
    subscriptionStatus: string;
    genderPreference?: Gender;
    gender: Gender;
    profileComplete: boolean;
    lastSeen: Timestamp;
    location: string;
}> {
    return {
        age: value.age,
        bio: value.bio,
        height: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.height)),
        filters: from_candid_DiscoveryFilters_n21(_uploadFile, _downloadFile, value.filters),
        photoKeys: await from_candid_vec_n26(_uploadFile, _downloadFile, value.photoKeys),
        profilePicUrl: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.profilePicUrl)),
        principal: value.principal,
        interests: value.interests,
        isPremium: value.isPremium,
        coverPicUrl: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.coverPicUrl)),
        premiumActivatedAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.premiumActivatedAt)),
        name: value.name,
        createdAt: value.createdAt,
        superLikesRemaining: value.superLikesRemaining,
        isDemo: value.isDemo,
        subscriptionStatus: value.subscriptionStatus,
        genderPreference: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.genderPreference)),
        gender: from_candid_Gender_n24(_uploadFile, _downloadFile, value.gender),
        profileComplete: value.profileComplete,
        lastSeen: value.lastSeen,
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interests: Array<string>;
    minAge: bigint;
    genderPref: [] | [_Gender];
    maxAge: bigint;
}): {
    interests: Array<string>;
    minAge: bigint;
    genderPref?: Gender;
    maxAge: bigint;
} {
    return {
        interests: value.interests,
        minAge: value.minAge,
        genderPref: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.genderPref)),
        maxAge: value.maxAge
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextOffset: [] | [bigint];
    profiles: Array<_Profile>;
}): Promise<{
    nextOffset?: bigint;
    profiles: Array<Profile>;
}> {
    return {
        nextOffset: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nextOffset)),
        profiles: await from_candid_vec_n32(_uploadFile, _downloadFile, value.profiles)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    premiumActivatedAt: [] | [bigint];
    subscriptionStatus: string;
}): {
    isPremium: boolean;
    premiumActivatedAt?: bigint;
    subscriptionStatus: string;
} {
    return {
        isPremium: value.isPremium,
        premiumActivatedAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.premiumActivatedAt)),
        subscriptionStatus: value.subscriptionStatus
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchId: [] | [_MatchId];
    matched: boolean;
}): {
    matchId?: MatchId;
    matched: boolean;
} {
    return {
        matchId: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.matchId)),
        matched: value.matched
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    nonBinary: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : "nonBinary" in value ? Gender.nonBinary : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Promise<Array<Profile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Profile_n19(_uploadFile, _downloadFile, x)));
}
function to_candid_DiscoveryFilters_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscoveryFilters): _DiscoveryFilters {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ProfileInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileInput): Promise<_ProfileInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SwipeAction_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SwipeAction): _SwipeAction {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bio: string;
    height?: bigint;
    photoKeys: Array<ExternalBlob>;
    interests: Array<string>;
    name: string;
    genderPreference?: Gender;
    gender: Gender;
    coverPic?: string;
    profilePic?: string;
    location: string;
}): Promise<{
    age: bigint;
    bio: string;
    height: [] | [bigint];
    photoKeys: Array<_ExternalBlob>;
    interests: Array<string>;
    name: string;
    genderPreference: [] | [_Gender];
    gender: _Gender;
    coverPic: [] | [string];
    profilePic: [] | [string];
    location: string;
}> {
    return {
        age: value.age,
        bio: value.bio,
        height: value.height ? candid_some(value.height) : candid_none(),
        photoKeys: await to_candid_vec_n12(_uploadFile, _downloadFile, value.photoKeys),
        interests: value.interests,
        name: value.name,
        genderPreference: value.genderPreference ? candid_some(to_candid_Gender_n14(_uploadFile, _downloadFile, value.genderPreference)) : candid_none(),
        gender: to_candid_Gender_n14(_uploadFile, _downloadFile, value.gender),
        coverPic: value.coverPic ? candid_some(value.coverPic) : candid_none(),
        profilePic: value.profilePic ? candid_some(value.profilePic) : candid_none(),
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    interests: Array<string>;
    minAge: bigint;
    genderPref?: Gender;
    maxAge: bigint;
}): {
    interests: Array<string>;
    minAge: bigint;
    genderPref: [] | [_Gender];
    maxAge: bigint;
} {
    return {
        interests: value.interests,
        minAge: value.minAge,
        genderPref: value.genderPref ? candid_some(to_candid_Gender_n14(_uploadFile, _downloadFile, value.genderPref)) : candid_none(),
        maxAge: value.maxAge
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} | {
    nonBinary: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value == Gender.nonBinary ? {
        nonBinary: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SwipeAction): {
    like: null;
} | {
    pass: null;
} | {
    superLike: null;
} {
    return value == SwipeAction.like ? {
        like: null
    } : value == SwipeAction.pass ? {
        pass: null
    } : value == SwipeAction.superLike ? {
        superLike: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
